model_class: Dino

model_import: model.multimodal.vision.dino

hf_name: facebook/dinov3-vitl16-pretrain-lvd1689m
# facebook/dinov3-vitb16-pretrain-lvd1689m

embedding_dim: 1024

hidden_dim: 4096

dropout: 0.1

freeze: true
