model_class: E5

model_import: model.multimodal.text.e5

hf_name: intfloat/multilingual-e5-base

embedding_dim: 768

hidden_dim: 2048

dropout: 0.3

pooling: mean

normalize_embeddings: true

freeze: true


