model_class: EmbeddingModel

model_import: model.multimodal.text.embedding_model

hf_name: jinaai/jina-embeddings-v5-text-small

embedding_dim: 1024

hidden_dim: 4096

dropout: 0.2

pooling: mean

normalize_embeddings: true

freeze: true

trust_remote_code: true
