name: CrisisMMD

train_csv: data/CrisisMMD_v2.0/splits/train.csv
val_csv: data/CrisisMMD_v2.0/splits/dev.csv
test_csv: data/CrisisMMD_v2.0/splits/test.csv

text_column: tweet_text

image_column: image_file

label_column: enc_label

label_text_column: label

image_augmentation: false
text_augmentation: false

use_sse: true

sse_prob: 0.15

sse_same_class_prob: 0.9

class_names:
  - not_informative
  - informative


max_length: 28

num_classes: 2