name: DisasterNet

train_csv: data/disasterDataset/datasetDisaster/train_data.csv
val_csv: data/disasterDataset/datasetDisaster/val_data.csv
test_csv: data/disasterDataset/datasetDisaster/test_data.csv

text_column: post_text

image_column: image_path

label_column: enc_label

label_text_column: labels

text_augmentation: false 

class_names:
  - flood
  - huaico
  - landslide
  - forest fire
  - frost hail
  - lightning storm
  - drought

max_length: 120

num_classes: 7